# this file is for the ci flow for GitHub
name: CI

# Trigger on push or pull request to main (can add other branches later)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Install backend dependencies
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      # 4. Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      # 5. Run backend tests (placeholder for now)
      - name: Test backend
        working-directory: backend
        run: echo "No tests yet" # add in test later on

      # 6. Run frontend tests (placeholder for now)
      - name: Test frontend
        working-directory: frontend
        run: echo "No tests yet" # add in tests later on
